{% set name = "ale" %}
{% set version = "0.5.0" %}
package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/USGS-Astrogeology/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 81e0de8e576119ef7a2d861a97cdb419ff0cf86438e1f8d7f0532f4c3ec268d4

build:
  number: 1
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake >=3.10
  host:
    - python >=3
    - eigen
    - gsl
    - nlohmann_json
    - pip
  run:
    - eigen
    - gsl
    - networkx
    - nlohmann_json
    - numpy
    - numba
    - pvl
    - python >=3
    - python-dateutil
    - quaternion
    - scipy
    - spiceypy >=2.3.0
    - pyyaml

test:
  imports:
    - ale
  commands:
    - conda inspect linkages -p $PREFIX $PKG_NAME
    - test -e $PREFIX/lib/libale${SHLIB_EXT}
    - test -e $PREFIX/include/ale.h

about:
  home: https://github.com/USGS-Astrogeology/ale
  license: The Unlicense
  license_file: LICENSE
  summary: "Abstraction Library for Ephemerides (ALE) for extracting and processing planetary sensor ephemeris data."

extra:
  recipe-maintainers:
    - jlaura
    - jessemapel
