{% set name = "ale" %}
{% set version = "0.11.0" %}
package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/DOI-USGS/{{ name }}/archive/{{ version }}.tar.gz
  sha256: f8aaaaac2a82205d5c25f155567775225e4bde5863bb75eb0e3c47ee47810329
  patches:
    # - patches/0001-Address-gdal-warning.patch
    # - patches/0002-Fix-CrismIsisLabelNaifSpice-driver-to-handle-VNIR-an.patch

build:
  number: 0
  entry_points:
    - isd_generate = ale.isd_generate:main
  skip: true  # [py2k]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake >=3.15
    - make
    - eigen
    - brotli-python
  host:
    - python
    - nlohmann_json
    - pip
    - setuptools
  run:
    - networkx
    - {{ pin_compatible('nlohmann_json', min_pin='x.x', max_pin='x.x') }}
    - numpy
    - pvl >=1.0
    - python
    - python-dateutil
    - pytz
    - scipy >=1.4.0
    - spiceypy >=2.3.0
    - pyyaml
    - setuptools
    - brotli-python

test:
  requires:
    - setuptools
  imports:
    - ale
  commands:
    - test -e $PREFIX/lib/libale${SHLIB_EXT}  # [unix]
    - if not exist %LIBRARY_BIN%\ale.dll exit 1  # [win]
    - if not exist %LIBRARY_LIB%\ale.lib exit 1  # [win]
    - isd_generate --version

about:
  home: https://github.com/DOI-USGS/ale
  license: CC0-1.0
  license_file: LICENSE.md
  summary: Abstraction Library for Ephemerides (ALE) for extracting and processing planetary sensor ephemeris data.

extra:
  recipe-maintainers:
    - amystamile-usgs
    - acpaquette
    - chkim-usgs
