{% set name = "ale" %}
{% set version = "0.9.1" %}
package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/DOI-USGS/{{ name }}/archive/{{ version }}.tar.gz
  sha256: ce830a57333edfc6dea5265dcc14e351c520b64b9f19e790da60fccc3bfe6336

build:
  number: 0
  entry_points:
    - isd_generate = ale.isd_generate:main
  skip: true  # [py2k]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - cmake >=3.15
    - make
    - eigen
  host:
    - python
    - nlohmann_json
    - pip
    - setuptools
  run:
    - networkx
    - {{ pin_compatible('nlohmann_json', min_pin='x.x', max_pin='x.x') }}
    - numpy
    - pvl >=1.0
    - python
    - python-dateutil
    - pytz
    - scipy >=1.4.0
    - spiceypy >=2.3.0
    - pyyaml
    - setuptools

test:
  requires:
    - setuptools
  imports:
    - ale
  commands:
    - test -e $PREFIX/lib/libale${SHLIB_EXT}  # [unix]
    - if not exist %LIBRARY_BIN%\ale.dll exit 1  # [win]
    - if not exist %LIBRARY_LIB%\ale.lib exit 1  # [win]
    - isd_generate --version

about:
  home: https://github.com/DOI-USGS/ale
  license: CC0-1.0
  license_file: LICENSE.md
  summary: Abstraction Library for Ephemerides (ALE) for extracting and processing planetary sensor ephemeris data.

extra:
  recipe-maintainers:
    - jlaura
    - jessemapel
    - andrewannex
    - acpaquette
