{% set name = "ale" %}
{% set version = "0.4.0" %}
package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/USGS-Astrogeology/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 49406e1214e76be01d16b1b16205afa70984b996e26e9cde9c8913d86a427124
  patches:
     - patches/cmake_targets.patch

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake >=3.10
  host:
    - python >=3
    - eigen
    - gsl
    - nlohmann_json
    - pip
  run:
    - eigen
    - gsl
    - networkx
    - nlohmann_json
    - numpy
    - numba
    - pvl
    - python >=3
    - python-dateutil
    - quaternion
    - scipy
    - spiceypy
    - pyyaml

test:
  imports:
    - ale

about:
  home: https://github.com/USGS-Astrogeology/ale
  license: The Unlicense
  license_file: LICENSE
  summary: "Abstraction Library for Ephemerides (ALE) for extracting and processing planetary sensor ephemeris data."

extra:
  recipe-maintainers:
    - jlaura
    - jessemapel
