{% set name = "ale" %}
{% set version = "0.11.0" %}
package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/DOI-USGS/{{ name }}/archive/{{ version }}.tar.gz
  sha256: b7259b156182b374b66c76c2ab818dcd13f7a1881e6fc00aa6043b72fe357997

build:
  number: 3
  entry_points:
    - isd_generate = ale.isd_generate:main
  skip: true  # [py2k]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake >=3.15
    - make
    - eigen
  host:
    - python
    - nlohmann_json =3.11.2
    - pip
    - setuptools
  run:
    - networkx
    - {{ pin_compatible('nlohmann_json', min_pin='x.x.x', max_pin='x.x.x') }}
    - numpy
    - pvl >=1.0
    - python
    - python-dateutil
    - pytz
    - scipy >=1.4.0
    - spiceypy >=2.3.0
    - pyyaml
    - setuptools
    - brotli-python

test:
  requires:
    - setuptools
  imports:
    - ale
  commands:
    - test -e $PREFIX/lib/libale${SHLIB_EXT}  # [unix]
    - if not exist %LIBRARY_BIN%\ale.dll exit 1  # [win]
    - if not exist %LIBRARY_LIB%\ale.lib exit 1  # [win]
    - isd_generate --version

about:
  home: https://github.com/DOI-USGS/ale
  license: CC0-1.0
  license_file: LICENSE.md
  summary: Abstraction Library for Ephemerides (ALE) for extracting and processing planetary sensor ephemeris data.

extra:
  recipe-maintainers:
    - amystamile-usgs
    - jlaura
    - jessemapel
    - andrewannex
    - acpaquette
    - chkim-usgs
