travis:
  secure:
    BINSTAR_TOKEN: NqaDCnrU9it/BW4kVAs0quuuJZUTTtN0H12YcZMc+FRHu/YgKaMaYde56PzjdK86DvRVtGmr7OfMH+57RCUVleKYvbiI35ffe1AMHuM0VDFpEVJ8T5grYq1nv0Dn+po0/I0Q6CiUy8H8PAuoFVHyGcBcL0+ZElHNBCqZj8CpIqZmGAYwfhwpYR0UO267/8Gls22fhk7UBxuMTq7Qh9DtG329T2TgPhOjcvU1DBd/pT+DKKi0gzl7Qx+VIu26wmx36MZAMWYQPgRf2scl9feavG6mqdxW8rPKTAwYlXhuj1PTlnJio31O8NU54vJMhsIYXoFl/3s0QXpU19CtUmyKO9dJeBlaT8CrvOfoSXWL3K4i3ud/tz+m5gk/6VX60xh4L24H9SBb00/OVI5bG0+81ZjsppEM2578DAic6Jt3aMTCCGMYR1+P640VPHbQG2WQiJfA6VW8xBcGzNviFixL+iek3kDmtEDrUOIx82xfwO62jvn9zJIo5BvbdcmRb4lEns0bfOQ1Acvfu3WucnR7OV0lvNGS/sUCVuWSTnOWP/Cw+6o0mdvEWzeWaouUK1MmcZQeMYGKYSY6h7vm9quGRhANgjHvBfC/gViCPCKOIy1Cs+QSsdmpJOsgVSn+Yu+FNKPFUqSD8WknPCgwbScYwC34LLUb16VIHD0as93Mlhk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
min_py_ver: '36'
max_py_ver: '38'
